# Este archivo contiene la configuración para ejecutar pruebas automatizadas en GitHub Actions

name: Jest Test

on: [push]

jobs:
    run-lint:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [16.17.0]
        steps:
            - uses: actions/checkout@v3
            - name: Cache node modules
            uses: actions/cache@v2
            with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-
            - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run lint > eslint-report.html 2>&1 || true
            - uses: actions/upload-artifact@v2
            with:
                name: eslint-report
                path: eslint-report.html

    run-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [16.17.0]
        steps:
            - uses: actions/checkout@v3
            - name: Cache node modules
                uses: actions/cache@v2
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-
            - name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
            - uses: actions/upload-artifact@v2
                with:
                    name: test-results
                    path: ./tests/report/test_report.html

    run-create-result-report:
        runs-on: ubuntu-latest
        needs: [run-lint, run-test]
        if: ${{ needs.run-lint.result == 'success' || needs.run-test.result == 'success' }}
        steps:
            - name: Download ESLint Report
                uses: actions/download-artifact@v2
                with:
                name: eslint-report

            - name: Download Test Results
                uses: actions/download-artifact@v2
                with:
                name: test-results

            - name: Combine Reports
                run: |
                cat eslint-report.html > result-report.html
                cat ./tests/report/test_report.html >> result-report.html
                shell: bash

    send-email:
        runs-on: ubuntu-latest
        needs: result-reports
        if: ${{ needs.run-create-result-report.result == 'success' }}
        steps:
            - name: Upload Result Report
                uses: actions/upload-artifact@v2
                with:
                name: result-report
                path: result-report.html

            - name: Download Result Report
                uses: actions/download-artifact@v2
                with:
                name: result-report

            - name: Send Email
                uses: dawidd6/action-send-mail@v2
                with:
                server_address: smtp.gmail.com
                server_port: 587
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                subject: 'Test and ESLint Results'
                body: 'The result Jest test and ESLint results are attached.'
                from: ${{ secrets.EMAIL_USERNAME }}
                to: ${{ secrets.EMAIL_USERNAME }}
                attachments: |
                    ./result-report.html
