# Este archivo contiene la configuración para ejecutar pruebas automatizadas en GitHub Actions

name: Jest Test

on: [push]

jobs:
    run-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [16.17.0]
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test

    send-email:
        runs-on: ubuntu-latest
        needs: run-test
        if: ${{ needs.run-tests.outputs.job-status == 'success' }}
        steps:
            - name: Download Test Results
              uses: actions/download-artifact@v2
              with:
                  name: test-results
            - name: Send Email
              uses: dawidd6/action-send-mail@v2
              with:
                  server_address: smtp.gmail.com
                  server_port: 587
                  username: ${{ secrets.EMAIL_USERNAME }}
                  password: ${{ secrets.EMAIL_PASSWORD }}
                  subject: 'Test Results'
                  body: 'The test results are attached.'
                  from: ${{ secrets.EMAIL_USERNAME }}
                  to: ${{ secrets.EMAIL_RECIPIENT }}
                  attachments: |
                      ./test-results.xml
