# Este archivo contiene la configuración para ejecutar pruebas automatizadas y enviar un correo electrónico en GitHub Actions

name: Jest Test

on:
    push:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.17.0
            - name: Install Dependencies
              run: npm install
            - name: Run Tests
              run: npm test
            - name: Upload Test Results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: ./test-results.xml
            - name: Set up job status
              id: set_job_status
              run: echo ::set-output name=job-status::success
            - name: Set up job message
              id: set_job_message
              run: echo ::set-output name=job-message::"Tests passed successfully!"
