name: Linter

on:
    push:
        branches:
            - master

jobs:
    run-lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [16.17.0]
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run lint > eslint-report.txt 2>&1 || true
            - run: |
                  sed -i 's/src\//\nFile: src\//g' eslint-report.txt
                  sed -i 's/  \([0-9]\+\):\([0-9]\+\)/  Line \1, Column \2:/g' eslint-report.txt
                  sed -i 's/error \([^ ]\+\) \([^\n]\+\)/<\/div><div class="lint-result">Rule: \1<br>\2<\/div><div class="lint-result">/g' eslint-report.txt
                  echo "<!DOCTYPE html><html><head><style>body { font-family: Arial, sans-serif; } .lint-result { border: 1px solid #ccc; padding: 10px; margin: 10px; }</style></head><body><div class='lint-results'>" > eslint-report.html
                  cat eslint-report.txt >> eslint-report.html
                  echo "</div><p class='lint-summary'>Linting Summary:</p><p class='lint-summary'>✖ 3 problems (3 errors, 0 warnings)</p></body></html>" >> eslint-report.html
            - uses: actions/upload-artifact@v2
              with:
                  name: eslint-report
                  path: eslint-report.html

    send-email:
        runs-on: ubuntu-latest
        needs: run-lint
        if: ${{ needs.run-lint.result == 'success' }}
        steps:
            - name: Download ESLint Report
              uses: actions/download-artifact@v2
              with:
                  name: eslint-report

            - name: Send Lint Email
              uses: dawidd6/action-send-mail@v2
              with:
                  server_address: smtp.gmail.com
                  server_port: 587
                  username: ${{ secrets.EMAIL_USERNAME }}
                  password: ${{ secrets.EMAIL_PASSWORD }}
                  subject: 'Lint Results'
                  body: 'The ESLint results are attached.'
                  from: ${{ secrets.EMAIL_USERNAME }}
                  to: ${{ secrets.EMAIL_USERNAME }}
                  attachments: |
                      ./eslint-report.html
